// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"
)

const countCategories = `-- name: CountCategories :one
SELECT COUNT(*) FROM expense_categories
`

func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO expense_categories (id, name, slug)
VALUES (?, ?, ?)
RETURNING id, name, slug, created_at
`

type CreateCategoryParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.ID, arg.Name, arg.Slug)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM expense_categories WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, slug, created_at FROM expense_categories WHERE id = ? LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, id string) (ExpenseCategory, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, created_at FROM expense_categories WHERE slug = ? LIMIT 1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (ExpenseCategory, error) {
	row := q.db.QueryRowContext(ctx, getCategoryBySlug, slug)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, created_at FROM expense_categories ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]ExpenseCategory, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseCategory{}
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE expense_categories SET name = ?, slug = ? WHERE id = ? RETURNING id, name, slug, created_at
`

type UpdateCategoryParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRowContext(ctx, updateCategory, arg.Name, arg.Slug, arg.ID)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
