// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package db

import (
	"context"
	"database/sql"
)

const countClients = `-- name: CountClients :one
SELECT COUNT(*) FROM clients
`

func (q *Queries) CountClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (id, name, email, phone, company, address_street, address_city, address_state, address_zip, address_country)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, email, phone, company, address_street, address_city, address_state, address_zip, address_country, created_at, updated_at
`

type CreateClientParams struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Email          string         `json:"email"`
	Phone          sql.NullString `json:"phone"`
	Company        sql.NullString `json:"company"`
	AddressStreet  sql.NullString `json:"address_street"`
	AddressCity    sql.NullString `json:"address_city"`
	AddressState   sql.NullString `json:"address_state"`
	AddressZip     sql.NullString `json:"address_zip"`
	AddressCountry sql.NullString `json:"address_country"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Company,
		arg.AddressStreet,
		arg.AddressCity,
		arg.AddressState,
		arg.AddressZip,
		arg.AddressCountry,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Company,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZip,
		&i.AddressCountry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE id = ?
`

func (q *Queries) DeleteClient(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClient, id)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, name, email, phone, company, address_street, address_city, address_state, address_zip, address_country, created_at, updated_at FROM clients WHERE id = ? LIMIT 1
`

func (q *Queries) GetClient(ctx context.Context, id string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Company,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZip,
		&i.AddressCountry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByEmail = `-- name: GetClientByEmail :one
SELECT id, name, email, phone, company, address_street, address_city, address_state, address_zip, address_country, created_at, updated_at FROM clients WHERE email = ? LIMIT 1
`

func (q *Queries) GetClientByEmail(ctx context.Context, email string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByEmail, email)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Company,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZip,
		&i.AddressCountry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, email, phone, company, address_street, address_city, address_state, address_zip, address_country, created_at, updated_at FROM clients ORDER BY created_at DESC
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Company,
			&i.AddressStreet,
			&i.AddressCity,
			&i.AddressState,
			&i.AddressZip,
			&i.AddressCountry,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchClients = `-- name: SearchClients :many
SELECT id, name, email, phone, company, address_street, address_city, address_state, address_zip, address_country, created_at, updated_at FROM clients
WHERE name LIKE ? OR company LIKE ? OR email LIKE ?
ORDER BY name
`

type SearchClientsParams struct {
	Name    string         `json:"name"`
	Company sql.NullString `json:"company"`
	Email   string         `json:"email"`
}

func (q *Queries) SearchClients(ctx context.Context, arg SearchClientsParams) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, searchClients, arg.Name, arg.Company, arg.Email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Company,
			&i.AddressStreet,
			&i.AddressCity,
			&i.AddressState,
			&i.AddressZip,
			&i.AddressCountry,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET name = ?, email = ?, phone = ?, company = ?,
    address_street = ?, address_city = ?, address_state = ?,
    address_zip = ?, address_country = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, email, phone, company, address_street, address_city, address_state, address_zip, address_country, created_at, updated_at
`

type UpdateClientParams struct {
	Name           string         `json:"name"`
	Email          string         `json:"email"`
	Phone          sql.NullString `json:"phone"`
	Company        sql.NullString `json:"company"`
	AddressStreet  sql.NullString `json:"address_street"`
	AddressCity    sql.NullString `json:"address_city"`
	AddressState   sql.NullString `json:"address_state"`
	AddressZip     sql.NullString `json:"address_zip"`
	AddressCountry sql.NullString `json:"address_country"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClient,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Company,
		arg.AddressStreet,
		arg.AddressCity,
		arg.AddressState,
		arg.AddressZip,
		arg.AddressCountry,
		arg.ID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Company,
		&i.AddressStreet,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZip,
		&i.AddressCountry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
