// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expenses.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countExpenses = `-- name: CountExpenses :one
SELECT COUNT(*) FROM expenses
`

func (q *Queries) CountExpenses(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExpenses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (id, description, category_id, merchant_id, amount, date, receipt_path, notes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, description, category_id, merchant_id, amount, date, receipt_path, notes, created_at, updated_at
`

type CreateExpenseParams struct {
	ID          string         `json:"id"`
	Description string         `json:"description"`
	CategoryID  sql.NullString `json:"category_id"`
	MerchantID  sql.NullString `json:"merchant_id"`
	Amount      float64        `json:"amount"`
	Date        time.Time      `json:"date"`
	ReceiptPath sql.NullString `json:"receipt_path"`
	Notes       sql.NullString `json:"notes"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.ID,
		arg.Description,
		arg.CategoryID,
		arg.MerchantID,
		arg.Amount,
		arg.Date,
		arg.ReceiptPath,
		arg.Notes,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.CategoryID,
		&i.MerchantID,
		&i.Amount,
		&i.Date,
		&i.ReceiptPath,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses WHERE id = ?
`

func (q *Queries) DeleteExpense(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteExpense, id)
	return err
}

const getExpense = `-- name: GetExpense :one
SELECT id, description, category_id, merchant_id, amount, date, receipt_path, notes, created_at, updated_at FROM expenses WHERE id = ? LIMIT 1
`

func (q *Queries) GetExpense(ctx context.Context, id string) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getExpense, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.CategoryID,
		&i.MerchantID,
		&i.Amount,
		&i.Date,
		&i.ReceiptPath,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecentExpenses = `-- name: GetRecentExpenses :many
SELECT id, description, category_id, merchant_id, amount, date, receipt_path, notes, created_at, updated_at FROM expenses ORDER BY date DESC LIMIT ?
`

func (q *Queries) GetRecentExpenses(ctx context.Context, limit int64) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, getRecentExpenses, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.CategoryID,
			&i.MerchantID,
			&i.Amount,
			&i.Date,
			&i.ReceiptPath,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalExpenses = `-- name: GetTotalExpenses :one
SELECT COALESCE(SUM(amount), 0) as total FROM expenses
`

func (q *Queries) GetTotalExpenses(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalExpenses)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getTotalExpensesByCategory = `-- name: GetTotalExpensesByCategory :one
SELECT COALESCE(SUM(amount), 0) as total FROM expenses WHERE category_id = ?
`

func (q *Queries) GetTotalExpensesByCategory(ctx context.Context, categoryID sql.NullString) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalExpensesByCategory, categoryID)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getTotalExpensesByDateRange = `-- name: GetTotalExpensesByDateRange :one
SELECT COALESCE(SUM(amount), 0) as total FROM expenses WHERE date >= ? AND date <= ?
`

type GetTotalExpensesByDateRangeParams struct {
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date_2"`
}

func (q *Queries) GetTotalExpensesByDateRange(ctx context.Context, arg GetTotalExpensesByDateRangeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalExpensesByDateRange, arg.Date, arg.Date_2)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, description, category_id, merchant_id, amount, date, receipt_path, notes, created_at, updated_at FROM expenses ORDER BY date DESC
`

func (q *Queries) ListExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.CategoryID,
			&i.MerchantID,
			&i.Amount,
			&i.Date,
			&i.ReceiptPath,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByCategory = `-- name: ListExpensesByCategory :many
SELECT id, description, category_id, merchant_id, amount, date, receipt_path, notes, created_at, updated_at FROM expenses WHERE category_id = ? ORDER BY date DESC
`

func (q *Queries) ListExpensesByCategory(ctx context.Context, categoryID sql.NullString) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpensesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.CategoryID,
			&i.MerchantID,
			&i.Amount,
			&i.Date,
			&i.ReceiptPath,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByDateRange = `-- name: ListExpensesByDateRange :many
SELECT id, description, category_id, merchant_id, amount, date, receipt_path, notes, created_at, updated_at FROM expenses
WHERE date >= ? AND date <= ?
ORDER BY date DESC
`

type ListExpensesByDateRangeParams struct {
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date_2"`
}

func (q *Queries) ListExpensesByDateRange(ctx context.Context, arg ListExpensesByDateRangeParams) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpensesByDateRange, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.CategoryID,
			&i.MerchantID,
			&i.Amount,
			&i.Date,
			&i.ReceiptPath,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByMerchant = `-- name: ListExpensesByMerchant :many
SELECT id, description, category_id, merchant_id, amount, date, receipt_path, notes, created_at, updated_at FROM expenses WHERE merchant_id = ? ORDER BY date DESC
`

func (q *Queries) ListExpensesByMerchant(ctx context.Context, merchantID sql.NullString) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpensesByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.CategoryID,
			&i.MerchantID,
			&i.Amount,
			&i.Date,
			&i.ReceiptPath,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET description = ?, category_id = ?, merchant_id = ?, amount = ?,
    date = ?, receipt_path = ?, notes = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, description, category_id, merchant_id, amount, date, receipt_path, notes, created_at, updated_at
`

type UpdateExpenseParams struct {
	Description string         `json:"description"`
	CategoryID  sql.NullString `json:"category_id"`
	MerchantID  sql.NullString `json:"merchant_id"`
	Amount      float64        `json:"amount"`
	Date        time.Time      `json:"date"`
	ReceiptPath sql.NullString `json:"receipt_path"`
	Notes       sql.NullString `json:"notes"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, updateExpense,
		arg.Description,
		arg.CategoryID,
		arg.MerchantID,
		arg.Amount,
		arg.Date,
		arg.ReceiptPath,
		arg.Notes,
		arg.ID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.CategoryID,
		&i.MerchantID,
		&i.Amount,
		&i.Date,
		&i.ReceiptPath,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExpenseReceipt = `-- name: UpdateExpenseReceipt :one
UPDATE expenses SET receipt_path = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, description, category_id, merchant_id, amount, date, receipt_path, notes, created_at, updated_at
`

type UpdateExpenseReceiptParams struct {
	ReceiptPath sql.NullString `json:"receipt_path"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateExpenseReceipt(ctx context.Context, arg UpdateExpenseReceiptParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, updateExpenseReceipt, arg.ReceiptPath, arg.ID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.CategoryID,
		&i.MerchantID,
		&i.Amount,
		&i.Date,
		&i.ReceiptPath,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
