// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countInvoices = `-- name: CountInvoices :one
SELECT COUNT(*) FROM invoices
`

func (q *Queries) CountInvoices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInvoices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInvoicesByStatus = `-- name: CountInvoicesByStatus :one
SELECT COUNT(*) FROM invoices WHERE status = ?
`

func (q *Queries) CountInvoicesByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInvoicesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (id, number, client_id, status, issue_date, due_date, subtotal, tax_rate, tax_amount, total, notes, public_token)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, number, client_id, status, issue_date, due_date, subtotal, tax_rate, tax_amount, total, notes, public_token, created_at, updated_at
`

type CreateInvoiceParams struct {
	ID          string         `json:"id"`
	Number      string         `json:"number"`
	ClientID    string         `json:"client_id"`
	Status      string         `json:"status"`
	IssueDate   time.Time      `json:"issue_date"`
	DueDate     time.Time      `json:"due_date"`
	Subtotal    float64        `json:"subtotal"`
	TaxRate     float64        `json:"tax_rate"`
	TaxAmount   float64        `json:"tax_amount"`
	Total       float64        `json:"total"`
	Notes       sql.NullString `json:"notes"`
	PublicToken sql.NullString `json:"public_token"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, createInvoice,
		arg.ID,
		arg.Number,
		arg.ClientID,
		arg.Status,
		arg.IssueDate,
		arg.DueDate,
		arg.Subtotal,
		arg.TaxRate,
		arg.TaxAmount,
		arg.Total,
		arg.Notes,
		arg.PublicToken,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.ClientID,
		&i.Status,
		&i.IssueDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TaxRate,
		&i.TaxAmount,
		&i.Total,
		&i.Notes,
		&i.PublicToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices WHERE id = ?
`

func (q *Queries) DeleteInvoice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteInvoice, id)
	return err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, number, client_id, status, issue_date, due_date, subtotal, tax_rate, tax_amount, total, notes, public_token, created_at, updated_at FROM invoices WHERE id = ? LIMIT 1
`

func (q *Queries) GetInvoice(ctx context.Context, id string) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.ClientID,
		&i.Status,
		&i.IssueDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TaxRate,
		&i.TaxAmount,
		&i.Total,
		&i.Notes,
		&i.PublicToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByNumber = `-- name: GetInvoiceByNumber :one
SELECT id, number, client_id, status, issue_date, due_date, subtotal, tax_rate, tax_amount, total, notes, public_token, created_at, updated_at FROM invoices WHERE number = ? LIMIT 1
`

func (q *Queries) GetInvoiceByNumber(ctx context.Context, number string) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceByNumber, number)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.ClientID,
		&i.Status,
		&i.IssueDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TaxRate,
		&i.TaxAmount,
		&i.Total,
		&i.Notes,
		&i.PublicToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByToken = `-- name: GetInvoiceByToken :one
SELECT id, number, client_id, status, issue_date, due_date, subtotal, tax_rate, tax_amount, total, notes, public_token, created_at, updated_at FROM invoices WHERE public_token = ? LIMIT 1
`

func (q *Queries) GetInvoiceByToken(ctx context.Context, publicToken sql.NullString) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceByToken, publicToken)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.ClientID,
		&i.Status,
		&i.IssueDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TaxRate,
		&i.TaxAmount,
		&i.Total,
		&i.Notes,
		&i.PublicToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextInvoiceSequence = `-- name: GetNextInvoiceSequence :one
INSERT INTO invoice_sequences (client_prefix, year, last_number)
VALUES (?, ?, 1)
ON CONFLICT(client_prefix, year) DO UPDATE SET last_number = last_number + 1
RETURNING last_number
`

type GetNextInvoiceSequenceParams struct {
	ClientPrefix string `json:"client_prefix"`
	Year         int64  `json:"year"`
}

func (q *Queries) GetNextInvoiceSequence(ctx context.Context, arg GetNextInvoiceSequenceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextInvoiceSequence, arg.ClientPrefix, arg.Year)
	var last_number int64
	err := row.Scan(&last_number)
	return last_number, err
}

const getRecentInvoices = `-- name: GetRecentInvoices :many
SELECT id, number, client_id, status, issue_date, due_date, subtotal, tax_rate, tax_amount, total, notes, public_token, created_at, updated_at FROM invoices ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) GetRecentInvoices(ctx context.Context, limit int64) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, getRecentInvoices, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.ClientID,
			&i.Status,
			&i.IssueDate,
			&i.DueDate,
			&i.Subtotal,
			&i.TaxRate,
			&i.TaxAmount,
			&i.Total,
			&i.Notes,
			&i.PublicToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, number, client_id, status, issue_date, due_date, subtotal, tax_rate, tax_amount, total, notes, public_token, created_at, updated_at FROM invoices ORDER BY created_at DESC
`

func (q *Queries) ListInvoices(ctx context.Context) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.ClientID,
			&i.Status,
			&i.IssueDate,
			&i.DueDate,
			&i.Subtotal,
			&i.TaxRate,
			&i.TaxAmount,
			&i.Total,
			&i.Notes,
			&i.PublicToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByClient = `-- name: ListInvoicesByClient :many
SELECT id, number, client_id, status, issue_date, due_date, subtotal, tax_rate, tax_amount, total, notes, public_token, created_at, updated_at FROM invoices WHERE client_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListInvoicesByClient(ctx context.Context, clientID string) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoicesByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.ClientID,
			&i.Status,
			&i.IssueDate,
			&i.DueDate,
			&i.Subtotal,
			&i.TaxRate,
			&i.TaxAmount,
			&i.Total,
			&i.Notes,
			&i.PublicToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByStatus = `-- name: ListInvoicesByStatus :many
SELECT id, number, client_id, status, issue_date, due_date, subtotal, tax_rate, tax_amount, total, notes, public_token, created_at, updated_at FROM invoices WHERE status = ? ORDER BY created_at DESC
`

func (q *Queries) ListInvoicesByStatus(ctx context.Context, status string) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoicesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.ClientID,
			&i.Status,
			&i.IssueDate,
			&i.DueDate,
			&i.Subtotal,
			&i.TaxRate,
			&i.TaxAmount,
			&i.Total,
			&i.Notes,
			&i.PublicToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOverdueInvoices = `-- name: MarkOverdueInvoices :exec
UPDATE invoices
SET status = 'overdue', updated_at = CURRENT_TIMESTAMP
WHERE status = 'sent' AND due_date < date('now')
`

func (q *Queries) MarkOverdueInvoices(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markOverdueInvoices)
	return err
}

const updateInvoice = `-- name: UpdateInvoice :one
UPDATE invoices
SET client_id = ?, status = ?, issue_date = ?, due_date = ?,
    subtotal = ?, tax_rate = ?, tax_amount = ?, total = ?,
    notes = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, number, client_id, status, issue_date, due_date, subtotal, tax_rate, tax_amount, total, notes, public_token, created_at, updated_at
`

type UpdateInvoiceParams struct {
	ClientID  string         `json:"client_id"`
	Status    string         `json:"status"`
	IssueDate time.Time      `json:"issue_date"`
	DueDate   time.Time      `json:"due_date"`
	Subtotal  float64        `json:"subtotal"`
	TaxRate   float64        `json:"tax_rate"`
	TaxAmount float64        `json:"tax_amount"`
	Total     float64        `json:"total"`
	Notes     sql.NullString `json:"notes"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, updateInvoice,
		arg.ClientID,
		arg.Status,
		arg.IssueDate,
		arg.DueDate,
		arg.Subtotal,
		arg.TaxRate,
		arg.TaxAmount,
		arg.Total,
		arg.Notes,
		arg.ID,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.ClientID,
		&i.Status,
		&i.IssueDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TaxRate,
		&i.TaxAmount,
		&i.Total,
		&i.Notes,
		&i.PublicToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoices SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, number, client_id, status, issue_date, due_date, subtotal, tax_rate, tax_amount, total, notes, public_token, created_at, updated_at
`

type UpdateInvoiceStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, updateInvoiceStatus, arg.Status, arg.ID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.ClientID,
		&i.Status,
		&i.IssueDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TaxRate,
		&i.TaxAmount,
		&i.Total,
		&i.Notes,
		&i.PublicToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvoiceTotals = `-- name: UpdateInvoiceTotals :one
UPDATE invoices
SET subtotal = ?, tax_amount = ?, total = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, number, client_id, status, issue_date, due_date, subtotal, tax_rate, tax_amount, total, notes, public_token, created_at, updated_at
`

type UpdateInvoiceTotalsParams struct {
	Subtotal  float64 `json:"subtotal"`
	TaxAmount float64 `json:"tax_amount"`
	Total     float64 `json:"total"`
	ID        string  `json:"id"`
}

func (q *Queries) UpdateInvoiceTotals(ctx context.Context, arg UpdateInvoiceTotalsParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, updateInvoiceTotals,
		arg.Subtotal,
		arg.TaxAmount,
		arg.Total,
		arg.ID,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.ClientID,
		&i.Status,
		&i.IssueDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TaxRate,
		&i.TaxAmount,
		&i.Total,
		&i.Notes,
		&i.PublicToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
