// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package db

import (
	"context"
	"time"
)

const getClientInvoiceCount = `-- name: GetClientInvoiceCount :one
SELECT COUNT(*) as count FROM invoices WHERE client_id = ?
`

func (q *Queries) GetClientInvoiceCount(ctx context.Context, clientID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getClientInvoiceCount, clientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getClientTotalBilled = `-- name: GetClientTotalBilled :one
SELECT COALESCE(SUM(total), 0) as total
FROM invoices
WHERE client_id = ? AND status = 'paid'
`

func (q *Queries) GetClientTotalBilled(ctx context.Context, clientID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getClientTotalBilled, clientID)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getExpensesByCategory = `-- name: GetExpensesByCategory :many
SELECT
    ec.name as category_name,
    ec.slug as category_slug,
    COALESCE(SUM(e.amount), 0) as total
FROM expense_categories ec
LEFT JOIN expenses e ON e.category_id = ec.id
GROUP BY ec.id, ec.name, ec.slug
ORDER BY total DESC
`

type GetExpensesByCategoryRow struct {
	CategoryName string      `json:"category_name"`
	CategorySlug string      `json:"category_slug"`
	Total        interface{} `json:"total"`
}

func (q *Queries) GetExpensesByCategory(ctx context.Context) ([]GetExpensesByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpensesByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExpensesByCategoryRow{}
	for rows.Next() {
		var i GetExpensesByCategoryRow
		if err := rows.Scan(&i.CategoryName, &i.CategorySlug, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvoiceStatusCounts = `-- name: GetInvoiceStatusCounts :many
SELECT status, COUNT(*) as count FROM invoices GROUP BY status
`

type GetInvoiceStatusCountsRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetInvoiceStatusCounts(ctx context.Context) ([]GetInvoiceStatusCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getInvoiceStatusCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInvoiceStatusCountsRow{}
	for rows.Next() {
		var i GetInvoiceStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyExpenses = `-- name: GetMonthlyExpenses :many
SELECT
    strftime('%m', date) as month,
    COALESCE(SUM(amount), 0) as expenses
FROM expenses
WHERE strftime('%Y', date) = ?
GROUP BY strftime('%m', date)
ORDER BY month
`

type GetMonthlyExpensesRow struct {
	Month    interface{} `json:"month"`
	Expenses interface{} `json:"expenses"`
}

func (q *Queries) GetMonthlyExpenses(ctx context.Context, date time.Time) ([]GetMonthlyExpensesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyExpenses, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyExpensesRow{}
	for rows.Next() {
		var i GetMonthlyExpensesRow
		if err := rows.Scan(&i.Month, &i.Expenses); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyRevenue = `-- name: GetMonthlyRevenue :many
SELECT
    strftime('%m', issue_date) as month,
    COALESCE(SUM(CASE WHEN status = 'paid' THEN total ELSE 0 END), 0) as revenue
FROM invoices
WHERE strftime('%Y', issue_date) = ?
GROUP BY strftime('%m', issue_date)
ORDER BY month
`

type GetMonthlyRevenueRow struct {
	Month   interface{} `json:"month"`
	Revenue interface{} `json:"revenue"`
}

func (q *Queries) GetMonthlyRevenue(ctx context.Context, issueDate time.Time) ([]GetMonthlyRevenueRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyRevenue, issueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyRevenueRow{}
	for rows.Next() {
		var i GetMonthlyRevenueRow
		if err := rows.Scan(&i.Month, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutstandingAmount = `-- name: GetOutstandingAmount :one
SELECT COALESCE(SUM(total), 0) as total
FROM invoices
WHERE status IN ('sent', 'overdue')
`

func (q *Queries) GetOutstandingAmount(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getOutstandingAmount)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getTotalExpensesByYear = `-- name: GetTotalExpensesByYear :one
SELECT COALESCE(SUM(amount), 0) as total
FROM expenses
WHERE strftime('%Y', date) = ?
`

func (q *Queries) GetTotalExpensesByYear(ctx context.Context, date time.Time) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalExpensesByYear, date)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getTotalRevenue = `-- name: GetTotalRevenue :one
SELECT COALESCE(SUM(total), 0) as total
FROM invoices
WHERE status = 'paid'
`

func (q *Queries) GetTotalRevenue(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalRevenue)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getTotalRevenueByYear = `-- name: GetTotalRevenueByYear :one
SELECT COALESCE(SUM(total), 0) as total
FROM invoices
WHERE status = 'paid' AND strftime('%Y', issue_date) = ?
`

func (q *Queries) GetTotalRevenueByYear(ctx context.Context, issueDate time.Time) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalRevenueByYear, issueDate)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getUpcomingDueInvoices = `-- name: GetUpcomingDueInvoices :many
SELECT id, number, client_id, status, issue_date, due_date, subtotal, tax_rate, tax_amount, total, notes, public_token, created_at, updated_at FROM invoices
WHERE status = 'sent' AND due_date <= date('now', '+7 days')
ORDER BY due_date
`

func (q *Queries) GetUpcomingDueInvoices(ctx context.Context) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingDueInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.ClientID,
			&i.Status,
			&i.IssueDate,
			&i.DueDate,
			&i.Subtotal,
			&i.TaxRate,
			&i.TaxAmount,
			&i.Total,
			&i.Notes,
			&i.PublicToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
