// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Client struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Email          string         `json:"email"`
	Phone          sql.NullString `json:"phone"`
	Company        sql.NullString `json:"company"`
	AddressStreet  sql.NullString `json:"address_street"`
	AddressCity    sql.NullString `json:"address_city"`
	AddressState   sql.NullString `json:"address_state"`
	AddressZip     sql.NullString `json:"address_zip"`
	AddressCountry sql.NullString `json:"address_country"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type Expense struct {
	ID          string         `json:"id"`
	Description string         `json:"description"`
	CategoryID  sql.NullString `json:"category_id"`
	MerchantID  sql.NullString `json:"merchant_id"`
	Amount      float64        `json:"amount"`
	Date        time.Time      `json:"date"`
	ReceiptPath sql.NullString `json:"receipt_path"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ExpenseCategory struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	Slug      string       `json:"slug"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Invoice struct {
	ID          string         `json:"id"`
	Number      string         `json:"number"`
	ClientID    string         `json:"client_id"`
	Status      string         `json:"status"`
	IssueDate   time.Time      `json:"issue_date"`
	DueDate     time.Time      `json:"due_date"`
	Subtotal    float64        `json:"subtotal"`
	TaxRate     float64        `json:"tax_rate"`
	TaxAmount   float64        `json:"tax_amount"`
	Total       float64        `json:"total"`
	Notes       sql.NullString `json:"notes"`
	PublicToken sql.NullString `json:"public_token"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type InvoiceSequence struct {
	ID           int64  `json:"id"`
	ClientPrefix string `json:"client_prefix"`
	Year         int64  `json:"year"`
	LastNumber   int64  `json:"last_number"`
}

type LineItem struct {
	ID          string       `json:"id"`
	InvoiceID   string       `json:"invoice_id"`
	Description string       `json:"description"`
	Quantity    float64      `json:"quantity"`
	Rate        float64      `json:"rate"`
	Amount      float64      `json:"amount"`
	SortOrder   int64        `json:"sort_order"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type Merchant struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}
