// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	CountCategories(ctx context.Context) (int64, error)
	CountClients(ctx context.Context) (int64, error)
	CountExpenses(ctx context.Context) (int64, error)
	CountInvoices(ctx context.Context) (int64, error)
	CountInvoicesByStatus(ctx context.Context, status string) (int64, error)
	CountLineItemsByInvoice(ctx context.Context, invoiceID string) (int64, error)
	CountMerchants(ctx context.Context) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (ExpenseCategory, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateLineItem(ctx context.Context, arg CreateLineItemParams) (LineItem, error)
	CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error)
	DeleteCategory(ctx context.Context, id string) error
	DeleteClient(ctx context.Context, id string) error
	DeleteExpense(ctx context.Context, id string) error
	DeleteInvoice(ctx context.Context, id string) error
	DeleteLineItem(ctx context.Context, id string) error
	DeleteLineItemsByInvoice(ctx context.Context, invoiceID string) error
	DeleteMerchant(ctx context.Context, id string) error
	GetCategory(ctx context.Context, id string) (ExpenseCategory, error)
	GetCategoryBySlug(ctx context.Context, slug string) (ExpenseCategory, error)
	GetClient(ctx context.Context, id string) (Client, error)
	GetClientByEmail(ctx context.Context, email string) (Client, error)
	GetClientInvoiceCount(ctx context.Context, clientID string) (int64, error)
	GetClientTotalBilled(ctx context.Context, clientID string) (interface{}, error)
	GetExpense(ctx context.Context, id string) (Expense, error)
	GetExpensesByCategory(ctx context.Context) ([]GetExpensesByCategoryRow, error)
	GetInvoice(ctx context.Context, id string) (Invoice, error)
	GetInvoiceByNumber(ctx context.Context, number string) (Invoice, error)
	GetInvoiceByToken(ctx context.Context, publicToken sql.NullString) (Invoice, error)
	GetInvoiceStatusCounts(ctx context.Context) ([]GetInvoiceStatusCountsRow, error)
	GetLineItem(ctx context.Context, id string) (LineItem, error)
	GetMerchant(ctx context.Context, id string) (Merchant, error)
	GetMerchantByName(ctx context.Context, name string) (Merchant, error)
	GetMonthlyExpenses(ctx context.Context, date time.Time) ([]GetMonthlyExpensesRow, error)
	GetMonthlyRevenue(ctx context.Context, issueDate time.Time) ([]GetMonthlyRevenueRow, error)
	GetNextInvoiceSequence(ctx context.Context, arg GetNextInvoiceSequenceParams) (int64, error)
	GetOutstandingAmount(ctx context.Context) (interface{}, error)
	GetRecentExpenses(ctx context.Context, limit int64) ([]Expense, error)
	GetRecentInvoices(ctx context.Context, limit int64) ([]Invoice, error)
	GetTotalExpenses(ctx context.Context) (interface{}, error)
	GetTotalExpensesByCategory(ctx context.Context, categoryID sql.NullString) (interface{}, error)
	GetTotalExpensesByDateRange(ctx context.Context, arg GetTotalExpensesByDateRangeParams) (interface{}, error)
	GetTotalExpensesByYear(ctx context.Context, date time.Time) (interface{}, error)
	GetTotalRevenue(ctx context.Context) (interface{}, error)
	GetTotalRevenueByYear(ctx context.Context, issueDate time.Time) (interface{}, error)
	GetUpcomingDueInvoices(ctx context.Context) ([]Invoice, error)
	ListCategories(ctx context.Context) ([]ExpenseCategory, error)
	ListClients(ctx context.Context) ([]Client, error)
	ListExpenses(ctx context.Context) ([]Expense, error)
	ListExpensesByCategory(ctx context.Context, categoryID sql.NullString) ([]Expense, error)
	ListExpensesByDateRange(ctx context.Context, arg ListExpensesByDateRangeParams) ([]Expense, error)
	ListExpensesByMerchant(ctx context.Context, merchantID sql.NullString) ([]Expense, error)
	ListInvoices(ctx context.Context) ([]Invoice, error)
	ListInvoicesByClient(ctx context.Context, clientID string) ([]Invoice, error)
	ListInvoicesByStatus(ctx context.Context, status string) ([]Invoice, error)
	ListLineItemsByInvoice(ctx context.Context, invoiceID string) ([]LineItem, error)
	ListMerchants(ctx context.Context) ([]Merchant, error)
	MarkOverdueInvoices(ctx context.Context) error
	SearchClients(ctx context.Context, arg SearchClientsParams) ([]Client, error)
	SearchMerchants(ctx context.Context, name string) ([]Merchant, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (ExpenseCategory, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error)
	UpdateExpenseReceipt(ctx context.Context, arg UpdateExpenseReceiptParams) (Expense, error)
	UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (Invoice, error)
	UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error)
	UpdateInvoiceTotals(ctx context.Context, arg UpdateInvoiceTotalsParams) (Invoice, error)
	UpdateLineItem(ctx context.Context, arg UpdateLineItemParams) (LineItem, error)
	UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) (Merchant, error)
}

var _ Querier = (*Queries)(nil)
